services:
  - docker
script:
  - docker image build -t shivambhat1997/imagetest .
deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push shivambhat1997/imagetest 
